name: Frontend

on:
  push:
    branches: [ "main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Build
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/museum-mate-frontend:latest .

      # 도커허브 로그인
      - name: Docker Image Push to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/museum-mate-frontend:latest

      # EC2 
      - name: Remote EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          key: ${{ secrets.EC2_KEY }}
          username: ubuntu
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/museum-mate-frontend:latest
            docker compose -f /home/ubuntu/docker/museum-mate/nginx/compose/docker-compose.yml up -d
            docker image prune -f
